function localTracks(){return currentGame?.musicTracks||[]}
function ensureLocalAudio(){const tracks=localTracks();if(!tracks.length)return null;if(musicIndex>=tracks.length)musicIndex=0;const src=tracks[musicIndex].src;if(!musicAudio||musicAudio.datasetSrc!==src){if(musicAudio)musicAudio.pause();musicAudio=new Audio(src);musicAudio.datasetSrc=src;musicAudio.onended=()=>{musicIndex=(musicIndex+1)%tracks.length;musicAudio=null;if(localPlaying)playLocal();renderLocalTracks()};musicAudio.onerror=()=>msg('Unable to play uploaded music');applyLocalVolume()}return musicAudio}
function playLocal(){const a=ensureLocalAudio();if(!a)return msg('No uploaded music in this game');localPlaying=true;a.play().catch(()=>msg('Tap Play again to allow audio'));renderMusicState()}
function pauseLocal(){localPlaying=false;if(musicAudio)musicAudio.pause();renderMusicState()}
function nextLocal(){const tracks=localTracks();if(!tracks.length)return msg('No uploaded tracks');const was=localPlaying;if(musicAudio)musicAudio.pause();musicIndex=(musicIndex+1)%tracks.length;musicAudio=null;if(was)playLocal();renderLocalTracks();msg('Next uploaded track')}
function nextSpotify(){if(!spotifyController||!spotifyReady)return msg('Spotify is still loading');const wasPlaying=spotifyPlaying;const jump=spotifyDurationMs>0?Math.ceil(spotifyDurationMs/1000)+1:24*60*60;try{spotifyController.seek(jump);if(!wasPlaying){setTimeout(()=>spotifyController.play(),80)}else{setTimeout(()=>spotifyController.resume(),80)}msg('Skipping Spotify track…')}catch(_e){msg('Use the Next control inside Spotify player')}}
function stopMusic(){resumeSpotifyAfterAnnouncement=false;localPlaying=false;if(musicAudio){musicAudio.pause();musicAudio.currentTime=0}if(previewAudio){previewAudio.pause();previewAudio.currentTime=0;previewAudio=null;previewKind=null}if(spotifyController)spotifyController.pause();spotifyPlaying=false;renderMusicState();msg('All music stopped')}
function stopAllAudio(){stopMusic();stopAnnouncement();$('now').innerHTML='<b>Stopped.</b> All app-controlled audio is off.'}
function setMusicSource(source){musicSource=source;if(source==='LOCAL'){if(spotifyController)spotifyController.pause();spotifyPlaying=false}else pauseLocal();renderMusicState()}
function renderMusicState(){$('localSourceBtn').classList.toggle('on',musicSource==='LOCAL');$('spotifySourceBtn').classList.toggle('on',musicSource==='SPOTIFY');$('dockSource').textContent=musicSource==='LOCAL'?'Uploaded Music':'Spotify';$('dockDetail').textContent=announcementActive?(musicSource==='LOCAL'?'Playing • ducked −3 dB':'Playing • Spotify/device volume'):(musicSource==='LOCAL'?'Uploaded music mixer active':'Spotify player active');const playing=musicSource==='LOCAL'?localPlaying:spotifyPlaying;$('musicPlayBtn').textContent=playing?'Ⅱ PAUSE MUSIC':'▶ PLAY MUSIC';$('nextTrackBtn').disabled=musicSource==='SPOTIFY'&&!spotifyReady;$('nextTrackBtn').style.opacity=$('nextTrackBtn').disabled?'.45':'1'}
$('localSourceBtn').onclick=()=>setMusicSource('LOCAL');$('spotifySourceBtn').onclick=()=>setMusicSource('SPOTIFY');$('musicPlayBtn').onclick=()=>{if(gameState==='LIVE')return msg('Music locked during live play');if(musicSource==='LOCAL'){localPlaying?pauseLocal():playLocal()}else{if(!spotifyController)return msg('Spotify is still loading');spotifyPlaying?spotifyController.pause():spotifyController.play()}};$('nextTrackBtn').onclick=()=>musicSource==='LOCAL'?nextLocal():nextSpotify();$('stopMusic').onclick=stopMusic;
$('musicVolume').oninput=e=>{musicVolume=Number(e.target.value)/100;$('musicVolumeLabel').textContent=Math.round(musicVolume*100)+'%';applyLocalVolume();if(previewAudio&&previewKind==='music')previewAudio.volume=musicVolume};$('musicVolume').onchange=()=>{if(musicSource==='SPOTIFY')msg('Spotify Embed volume is controlled by Spotify/the device')};
$('soundVolume').oninput=e=>{soundVolume=Number(e.target.value)/100;$('soundVolumeLabel').textContent=Math.round(soundVolume*100)+'%';applySoundVolume()};
$('stopAllAudio').onclick=stopAllAudio;
function renderLocalTracks(){const tracks=localTracks();$('localTracks').innerHTML=tracks.length?tracks.map((t,i)=>`<div class="track"><div class="meta"><b>${escapeHtml(t.name)}</b><small>${i===musicIndex?'Current track':'Uploaded music'}</small></div><button class="mini" data-play-track="${i}">${i===musicIndex&&localPlaying?'Playing':'Play'}</button></div>`).join(''):'<div class="tiny">No uploaded tracks in this published game.</div>';$('localTracks').querySelectorAll('[data-play-track]').forEach(b=>b.onclick=()=>{musicIndex=Number(b.dataset.playTrack);if(musicAudio)musicAudio.pause();musicAudio=null;setMusicSource('LOCAL');playLocal();renderLocalTracks()})}

function setState(next){gameState=next;document.querySelectorAll('#statebar button').forEach(b=>b.classList.toggle('on',b.dataset.state===next));const names={BREAK:'BETWEEN PLAYS',LIVE:'LIVE PLAY',TIMEOUT:'TIMEOUT',HALFTIME:'HALFTIME',FINAL:'FINAL'};if(next==='LIVE'){stopMusic();stopAnnouncement();$('now').innerHTML='<b>LIVE PLAY.</b> All app-controlled audio stopped.';msg('Live Play — audio stopped')}$('cloudStatus').textContent=currentGame?`CLOUD GAME • v${currentGame.version} • ${names[next]}`:`PUBLIC • ${names[next]}`;renderMusicState()}
$('statebar').onclick=e=>{const b=e.target.closest('button[data-state]');if(b)setState(b.dataset.state)};

window.onSpotifyIframeApiReady=(IFrameAPI)=>{const mount=$('spotifyMount');const url=currentGame?.spotifyUrl||DEFAULT_SPOTIFY;IFrameAPI.createController(mount,{url,width:'100%',height:352},controller=>{spotifyController=controller;spotifyReady=true;$('spotifyStatus').textContent='READY';renderMusicState();controller.addListener('playback_started',e=>{spotifyPlaying=true;spotifyPlayingUri=e?.data?.playingURI||spotifyPlayingUri;spotifyDurationMs=0;spotifyPositionMs=0;renderMusicState()});controller.addListener('playback_update',e=>{spotifyPlaying=!e.data.isPaused;spotifyDurationMs=Number(e.data.duration)||spotifyDurationMs;spotifyPositionMs=Number(e.data.position)||0;spotifyPlayingUri=e.data.playingURI||spotifyPlayingUri;renderMusicState()});});};
function loadSpotifyPlaylist(url){if(!spotifyController)return;spotifyDurationMs=0;spotifyPositionMs=0;spotifyPlayingUri='';const value=url||DEFAULT_SPOTIFY;spotifyController.loadEntity(value);}
const spotifyScript=document.createElement('script');spotifyScript.src='https://open.spotify.com/embed/iframe-api/v1';spotifyScript.async=true;document.body.appendChild(spotifyScript);
async function loadPublishedGame(slug){$('cloudStatus').textContent='LOADING CLOUD GAME';try{const r=await fetch(SB_URL+'/functions/v1/published-game?slug='+encodeURIComponent(slug));if(!r.ok)throw new Error('Game not found');currentGame=await r.json();$('gameTitle').textContent=currentGame.title;$('gameSub').textContent=currentGame.homeTeam+' vs '+currentGame.awayTeam+(currentGame.venue?' • '+currentGame.venue:'');$('brandSub').textContent=currentGame.presetName+' • Volunteer Audio Console';musicSource=currentGame.defaultMusicSource==='LOCAL'?'LOCAL':'SPOTIFY';renderBoard();renderLocalTracks();renderMusicState();loadSpotifyPlaylist(currentGame.spotifyUrl);setState('BREAK')}catch(e){$('cloudStatus').textContent='PUBLIC • NO LOGIN';msg(e.message||'Unable to load published game')}}

const params=new URLSearchParams(location.search);const adminMode=params.get('admin')==='1';if(adminMode){$('operator').classList.add('off');$('admin').classList.add('on');$('opLink').classList.remove('on');$('adminLink').classList.add('on');$('cloudStatus').textContent='ADMIN STUDIO';$('dockSource').textContent='Admin Preview'}else{const slug=params.get('game');renderBoard();renderLocalTracks();renderMusicState();if(slug)loadPublishedGame(slug)}

async function refreshSession(){const {data:{session}}=await supabase.auth.getSession();showSession(session)}
function showSession(session){$('authView').classList.toggle('hidden',!!session);$('studio').classList.toggle('hidden',!session);if(session){$('adminUser').textContent=session.user.email||session.user.id;loadAdminData(session.user)}}
