const createClient=window.__createClient;

const SB_URL='https://voynfqugirhtvmmmtpav.supabase.co';
const SB_KEY='sb_publishable_Kr-bunmKSsvr7coxFQLmbw_szgznA6W';
const DEFAULT_SPOTIFY='https://open.spotify.com/playlist/37i9dQZF1DX3Kdv0IChEm9';
const DUCK_FACTOR=.18;
const palette={orange:{tone:'#9b513f',bg:'#2b1b18'},blue:{tone:'#486da9',bg:'#172238'},green:{tone:'#397a5a',bg:'#14271f'},red:{tone:'#88404e',bg:'#301a20'},purple:{tone:'#77549f',bg:'#261d33'},yellow:{tone:'#9a7a35',bg:'#2b2416'},slate:{tone:'#48586d',bg:'#19212c'}};
const defaultSoundboard=[
{id:'opener',label:'Game Opener',eyebrow:'PRE-GAME',kind:'announcement',color:'orange',speechText:'Welcome to today’s youth football game. Please support our athletes, coaches, officials, and volunteers with positive sportsmanship.',assetId:''},
{id:'anthem',label:'National Anthem',eyebrow:'CEREMONY',kind:'announcement',color:'blue',speechText:'Ladies and gentlemen, please rise and remove your hats for the playing of our National Anthem.',assetId:''},
{id:'q1',label:'1st Quarter',eyebrow:'QUARTER',kind:'announcement',color:'blue',speechText:'The first quarter is underway.',assetId:''},{id:'q2',label:'2nd Quarter',eyebrow:'QUARTER',kind:'announcement',color:'blue',speechText:'We are beginning the second quarter.',assetId:''},{id:'halftime',label:'Halftime',eyebrow:'BREAK',kind:'announcement',color:'purple',speechText:'We have reached halftime.',assetId:''},{id:'q3',label:'3rd Quarter',eyebrow:'QUARTER',kind:'announcement',color:'blue',speechText:'We are beginning the third quarter.',assetId:''},{id:'q4',label:'4th Quarter',eyebrow:'QUARTER',kind:'announcement',color:'blue',speechText:'We are beginning the fourth quarter.',assetId:''},{id:'timeout',label:'Timeout',eyebrow:'GAME',kind:'announcement',color:'blue',speechText:'Timeout on the field.',assetId:''},{id:'flag',label:'Flag on the Play',eyebrow:'PENALTY',kind:'announcement',color:'orange',speechText:'There is a flag on the play.',assetId:''},{id:'touchdown',label:'Touchdown',eyebrow:'SCORE',kind:'announcement',color:'green',speechText:'Touchdown!',assetId:''},{id:'turnover',label:'Turnover',eyebrow:'CHANGE',kind:'announcement',color:'red',speechText:'Turnover. Possession changes hands.',assetId:''},{id:'first-down',label:'First Down',eyebrow:'FIRST DOWN',kind:'announcement',color:'green',speechText:'First down!',assetId:''},{id:'final',label:'End of Game',eyebrow:'FINAL',kind:'announcement',color:'red',speechText:'That is the end of the game. Thank you for supporting youth football today.',assetId:''}
];
const supabase=createClient(SB_URL,SB_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);const toast=$('toast');
let gameState='BREAK',currentGame=null,currentAnnouncement=null,announcementActive=false;
let soundVolume=.95,musicSource='SPOTIFY',musicVolume=.78,musicIndex=0,musicAudio=null,localPlaying=false;
let spotifyController=null,spotifyReady=false,spotifyPlaying=false,resumeSpotifyAfterAnnouncement=false,spotifyDurationMs=0,spotifyPositionMs=0,spotifyPlayingUri='';
let assets=[],soundboardDraft=structuredClone(defaultSoundboard),selectedMusicIds=[];
let previewAudio=null,previewKind=null;

function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function msg(t){toast.textContent=t;toast.classList.add('on');clearTimeout(window.__toast);window.__toast=setTimeout(()=>toast.classList.remove('on'),1600)}
function spotifyUri(url){const m=String(url||'').match(/open\.spotify\.com\/playlist\/([A-Za-z0-9]+)/);return m?'spotify:playlist:'+m[1]:null}
function setTab(group,name){document.querySelectorAll(`[data-${group}-tab]`).forEach(b=>b.classList.toggle('on',b.dataset[`${group}Tab`]===name));const map=group==='game'?{sound:'soundPane',music:'musicPane'}:{soundboard:'adminSoundboard',music:'adminMusic',publish:'adminPublish'};Object.entries(map).forEach(([k,id])=>$(id).classList.toggle('on',k===name))}
document.querySelectorAll('[data-game-tab]').forEach(b=>b.onclick=()=>setTab('game',b.dataset.gameTab));document.querySelectorAll('[data-admin-tab]').forEach(b=>b.onclick=()=>setTab('admin',b.dataset.adminTab));

function normalizeSoundItem(item){const knownAnnouncementIds=new Set(defaultSoundboard.map(x=>x.id));return {...item,kind:item.kind==='effect'?'effect':item.kind==='announcement'?'announcement':(knownAnnouncementIds.has(item.id)||item.speechText?'announcement':'effect')}}
function activeSoundboard(){const published=currentGame?.soundboardConfig;if(Array.isArray(published)&&published.length)return published.map(i=>normalizeSoundItem({...i,assetId:''}));return defaultSoundboard.map(normalizeSoundItem)}
function createSoundButton(item){const p=palette[item.color]||palette.slate;const b=document.createElement('button');b.className='sound'+(currentGame?.soundSources?.[item.id]?' cloud':'');b.style.setProperty('--tone',p.tone);b.style.setProperty('--tone-bg',p.bg);const small=document.createElement('small');small.textContent=item.eyebrow||'SOUND';const strong=document.createElement('strong');strong.textContent=item.label||'Untitled';b.append(small,strong);b.onclick=()=>playAnnouncement(item);return b}
function renderBoard(){const effects=$('effectsBoard'),announcements=$('announcementsBoard');effects.innerHTML='';announcements.innerHTML='';let effectCount=0,announcementCount=0;for(const raw of activeSoundboard()){const item=normalizeSoundItem(raw);if(item.kind==='effect'){effects.appendChild(createSoundButton(item));effectCount++}else{announcements.appendChild(createSoundButton(item));announcementCount++}}$('effectsEmpty').classList.toggle('hidden',effectCount>0);$('announcementsEmpty').classList.toggle('hidden',announcementCount>0)}
function applyLocalVolume(){if(musicAudio)musicAudio.volume=Math.max(0,Math.min(1,musicVolume*(announcementActive?DUCK_FACTOR:1)))}
function applySoundVolume(){if(currentAnnouncement)currentAnnouncement.volume=soundVolume;if(previewAudio&&previewKind==='sound')previewAudio.volume=soundVolume}
function stopAnnouncement(){if(currentAnnouncement){currentAnnouncement.pause();currentAnnouncement.currentTime=0;currentAnnouncement=null}if('speechSynthesis'in window)speechSynthesis.cancel();announcementActive=false;resumeSpotifyAfterAnnouncement=false;applyLocalVolume()}
function beginDuck(){announcementActive=true;applyLocalVolume();if(musicSource==='SPOTIFY'&&spotifyPlaying&&spotifyController){resumeSpotifyAfterAnnouncement=true;spotifyController.pause();}}
function endDuck(){announcementActive=false;applyLocalVolume();if(resumeSpotifyAfterAnnouncement&&gameState!=='LIVE'&&spotifyController){resumeSpotifyAfterAnnouncement=false;spotifyController.resume();}}
function speakFallback(text){if(!('speechSynthesis'in window)){endDuck();return}const u=new SpeechSynthesisUtterance(text||'');u.rate=.96;u.volume=soundVolume;u.onend=()=>{endDuck();$('now').innerHTML='<b>Ready.</b> No announcement playing.'};u.onerror=()=>endDuck();speechSynthesis.speak(u)}
function playAnnouncement(item){if(currentAnnouncement){currentAnnouncement.pause();currentAnnouncement=null}if('speechSynthesis'in window)speechSynthesis.cancel();beginDuck();$('now').innerHTML='<b>Now playing:</b> '+escapeHtml(item.label);const src=currentGame?.soundSources?.[item.id];if(src){const a=new Audio(src);a.volume=soundVolume;currentAnnouncement=a;a.onended=()=>{currentAnnouncement=null;endDuck();$('now').innerHTML='<b>Ready.</b> No announcement playing.'};a.onerror=()=>{currentAnnouncement=null;msg('Cloud audio failed; using device voice');speakFallback(item.speechText)};a.play().catch(()=>{currentAnnouncement=null;speakFallback(item.speechText)});}else speakFallback(item.speechText);msg('▶ '+item.label)}
