supabase.auth.onAuthStateChange((_event,session)=>showSession(session));refreshSession();
$('signIn').onclick=async()=>{const {error}=await supabase.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)msg(error.message);else msg('Signed in')};
$('signUp').onclick=async()=>{const {error}=await supabase.auth.signUp({email:$('email').value.trim(),password:$('password').value,emailRedirectTo:location.origin+location.pathname+'?admin=1'});if(error)msg(error.message);else msg('Account created. Check email if confirmation is required.')};
$('signOut').onclick=()=>supabase.auth.signOut();

async function loadAdminData(user){const [{data:a,error:ae},{data:p,error:pe}]=await Promise.all([supabase.from('audio_assets').select('id,name,kind,storage_path,created_at').order('created_at',{ascending:false}),supabase.from('admin_preferences').select('soundboard_draft,music_selection').eq('owner_id',user.id).maybeSingle()]);if(ae)msg(ae.message);assets=a||[];if(pe)msg(pe.message);if(p){if(Array.isArray(p.soundboard_draft)&&p.soundboard_draft.length)soundboardDraft=p.soundboard_draft.map(normalizeSoundItem);else soundboardDraft=structuredClone(defaultSoundboard);if(Array.isArray(p.music_selection))selectedMusicIds=p.music_selection;else selectedMusicIds=assets.filter(a=>a.kind==='music').map(a=>a.id)}else{soundboardDraft=structuredClone(defaultSoundboard);selectedMusicIds=assets.filter(a=>a.kind==='music').map(a=>a.id)}renderAdminAssets();renderSoundEditor();loadGames()}
function soundAssets(){return assets.filter(a=>a.kind==='sound')}function musicAssets(){return assets.filter(a=>a.kind==='music')}
function renderAdminAssets(){$('soundAssets').innerHTML=soundAssets().map(a=>`<div class="assetrow"><div><b>${escapeHtml(a.name)}</b><div class="tiny">SOUND</div></div><div class="row"><button class="mini" data-preview="${a.id}">Preview</button><button class="danger" data-del="${a.id}">Delete</button></div></div>`).join('')||'<div class="tiny">No uploaded sounds yet.</div>';$('musicAssets').innerHTML=musicAssets().map(a=>`<div class="assetrow"><div><label style="display:flex;gap:7px;align-items:center"><input type="checkbox" data-music-select="${a.id}" ${selectedMusicIds.includes(a.id)?'checked':''}><span><b>${escapeHtml(a.name)}</b><span class="tiny" style="display:block">MUSIC</span></span></label></div><div class="row"><button class="mini" data-preview="${a.id}">Preview</button><button class="danger" data-del="${a.id}">Delete</button></div></div>`).join('')||'<div class="tiny">No uploaded music yet.</div>';document.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>previewAsset(b.dataset.preview));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteAsset(b.dataset.del));document.querySelectorAll('[data-music-select]').forEach(c=>c.onchange=()=>{selectedMusicIds=Array.from(document.querySelectorAll('[data-music-select]:checked')).map(x=>x.dataset.musicSelect);savePreferences(false)})}
async function previewAsset(id){const asset=assets.find(a=>a.id===id);if(!asset)return;const {data,error}=await supabase.storage.from('gameday-audio').createSignedUrl(asset.storage_path,300);if(error)return msg(error.message);if(previewAudio){previewAudio.pause();previewAudio=null}previewKind=asset.kind;previewAudio=new Audio(data.signedUrl);previewAudio.crossOrigin='anonymous';if(typeof routeMedia==='function'){const routed=routeMedia(previewAudio,asset.kind==='music'?'music':'sound');if(!routed)previewAudio.volume=asset.kind==='music'?musicVolume:soundVolume}else previewAudio.volume=asset.kind==='music'?musicVolume:soundVolume;previewAudio.onended=()=>{previewAudio=null;previewKind=null};previewAudio.play().catch(()=>msg('Unable to preview audio'))}
async function assetReferenceCount(id){const {data,error}=await supabase.from('game_versions').select('id,sound_assignments,music_asset_ids');if(error)throw error;return (data||[]).filter(v=>Object.values(v.sound_assignments||{}).includes(id)||Array.isArray(v.music_asset_ids)&&v.music_asset_ids.includes(id)).length}
async function deleteAsset(id){const asset=assets.find(a=>a.id===id);if(!asset)return;let refs=0;try{refs=await assetReferenceCount(id)}catch(error){return msg(error.message||'Unable to check published game references')}if(refs>0)return msg('This audio is used by '+refs+' published game version'+(refs===1?'':'s')+'. Remove it from future versions instead of deleting the source file.');const {error}=await supabase.from('audio_assets').delete().eq('id',id);if(error)return msg(error.message);let storageError=null;if(asset.storage_path){const {error:removeError}=await supabase.storage.from('gameday-audio').remove([asset.storage_path]);storageError=removeError||null}assets=assets.filter(a=>a.id!==id);soundboardDraft=soundboardDraft.map(i=>i.assetId===id?{...i,assetId:''}:i);selectedMusicIds=selectedMusicIds.filter(x=>x!==id);renderAdminAssets();renderSoundEditor();await savePreferences(false);msg(storageError?'Audio removed from the library; storage cleanup will need retry.':'Audio deleted')}
async function uploadFile(kind,inputId){const f=$(inputId).files[0];if(!f)return msg('Choose an audio file');if(f.size>25*1024*1024)return msg('Audio files must be 25 MB or smaller');if(f.type&&!f.type.startsWith('audio/'))return msg('Choose a supported audio file');const {data:{user}}=await supabase.auth.getUser();if(!user)return msg('Sign in first');const ext=(f.name.split('.').pop()||'audio').replace(/[^a-z0-9]/gi,'').slice(0,12)||'audio';const key=crypto.randomUUID();const path=user.id+'/'+key+'.'+ext;const {error:upErr}=await supabase.storage.from('gameday-audio').upload(path,f,{contentType:f.type||'audio/mpeg',upsert:false});if(upErr)return msg(upErr.message);const {data:newAsset,error:dbErr}=await supabase.from('audio_assets').insert({owner_id:user.id,name:f.name,kind,mime_type:f.type||'audio/mpeg',size_bytes:f.size,storage_path:path,client_asset_key:key}).select('id,name,kind,storage_path,created_at').single();if(dbErr){await supabase.storage.from('gameday-audio').remove([path]);return msg(dbErr.message)}assets=[newAsset,...assets];if(kind==='music'&&!selectedMusicIds.includes(newAsset.id))selectedMusicIds.push(newAsset.id);$(inputId).value='';renderAdminAssets();renderSoundEditor();await savePreferences(false);msg(kind==='sound'?'Sound uploaded':'Music uploaded')}
$('uploadSound').onclick=()=>uploadFile('sound','soundFile');$('uploadMusic').onclick=()=>uploadFile('music','musicFile');
